#!/bin/bash

# =============================================================================
# Ortho Innovations - Patient App Deployment Script
# =============================================================================
# Usage: ./deploy.sh [--init|--update|--restart|--logs|--status]
# =============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Configuration
APP_NAME="ortho-patient-app"
REPO_URL="https://github.com/sileade/ortho-innovations.git"
INSTALL_DIR="/opt/ortho-innovations"
APP_DIR="$INSTALL_DIR/frontend/patient-app"
COMPOSE_FILE="docker-compose.dev.yml"

# Firebase Configuration (pre-configured)
FIREBASE_API_KEY="AIzaSyB_kgiOiqLwZkWq-ENi64GYyJSwAKK7dBQ"
FIREBASE_AUTH_DOMAIN="ortho-innovations.firebaseapp.com"
FIREBASE_PROJECT_ID="ortho-innovations"
FIREBASE_STORAGE_BUCKET="ortho-innovations.firebasestorage.app"
FIREBASE_MESSAGING_SENDER_ID="914686839626"
FIREBASE_APP_ID="1:914686839626:web:167c8a6ca7af14d85e4fb3"
FIREBASE_VAPID_KEY="BLvxBh3zA6oKMU-UGpFKgWumw5JfvFQL9Of26hwfarqJTfd_4WSxudNM8-0zikjVer7R3wFk5ELVlMrDyebQ6wQ"

# Functions
print_header() {
    echo -e "${BLUE}"
    echo "=============================================="
    echo "  Ortho Innovations - Patient App Deployer"
    echo "=============================================="
    echo -e "${NC}"
}

print_success() {
    echo -e "${GREEN}✓ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠ $1${NC}"
}

print_error() {
    echo -e "${RED}✗ $1${NC}"
}

print_info() {
    echo -e "${BLUE}ℹ $1${NC}"
}

check_dependencies() {
    print_info "Checking dependencies..."
    
    if ! command -v docker &> /dev/null; then
        print_error "Docker is not installed. Please install Docker first."
        exit 1
    fi
    
    if ! command -v docker compose &> /dev/null; then
        print_error "Docker Compose is not installed. Please install Docker Compose first."
        exit 1
    fi
    
    if ! command -v git &> /dev/null; then
        print_error "Git is not installed. Please install Git first."
        exit 1
    fi
    
    print_success "All dependencies are installed"
}

create_env_file() {
    print_info "Creating .env file with Firebase configuration..."
    
    cat > "$APP_DIR/.env" << EOF
# =============================================================================
# Ortho Innovations - Patient App Environment Variables
# Generated by deploy.sh on $(date)
# =============================================================================

# Database Configuration
DATABASE_URL=postgresql://ortho:\${DB_PASSWORD:-ortho123}@db:5432/ortho_patient
DB_PASSWORD=ortho123

# JWT Configuration
JWT_SECRET=\${JWT_SECRET:-your-super-secret-jwt-key-change-in-production}

# Application Configuration
NODE_ENV=production
VITE_APP_TITLE=Ortho Innovations

# Firebase Configuration (Push Notifications)
VITE_FIREBASE_API_KEY=$FIREBASE_API_KEY
VITE_FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN
VITE_FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
VITE_FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET
VITE_FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID
VITE_FIREBASE_APP_ID=$FIREBASE_APP_ID
VITE_FIREBASE_VAPID_KEY=$FIREBASE_VAPID_KEY
EOF

    print_success ".env file created"
}

init_deployment() {
    print_header
    print_info "Initializing fresh deployment..."
    
    check_dependencies
    
    # Clone repository if not exists
    if [ ! -d "$INSTALL_DIR" ]; then
        print_info "Cloning repository..."
        sudo mkdir -p "$INSTALL_DIR"
        sudo chown $USER:$USER "$INSTALL_DIR"
        git clone "$REPO_URL" "$INSTALL_DIR"
        print_success "Repository cloned"
    else
        print_warning "Directory $INSTALL_DIR already exists. Use --update instead."
        exit 1
    fi
    
    cd "$APP_DIR"
    
    # Create .env file
    create_env_file
    
    # Build and start containers
    print_info "Building and starting containers..."
    docker compose -f "$COMPOSE_FILE" up -d --build
    
    print_success "Deployment completed!"
    print_info "Application is running at http://localhost:3000"
    
    # Show status
    show_status
}

update_deployment() {
    print_header
    print_info "Updating deployment..."
    
    if [ ! -d "$INSTALL_DIR" ]; then
        print_error "Installation directory not found. Use --init first."
        exit 1
    fi
    
    cd "$INSTALL_DIR"
    
    # Pull latest changes
    print_info "Pulling latest changes from GitHub..."
    git pull origin main
    print_success "Code updated"
    
    cd "$APP_DIR"
    
    # Update .env file
    create_env_file
    
    # Rebuild and restart containers
    print_info "Rebuilding containers..."
    docker compose -f "$COMPOSE_FILE" down
    docker compose -f "$COMPOSE_FILE" up -d --build
    
    print_success "Update completed!"
    
    # Show status
    show_status
}

restart_deployment() {
    print_header
    print_info "Restarting containers..."
    
    cd "$APP_DIR"
    docker compose -f "$COMPOSE_FILE" restart
    
    print_success "Containers restarted"
    show_status
}

show_logs() {
    print_header
    print_info "Showing logs (Ctrl+C to exit)..."
    
    cd "$APP_DIR"
    docker compose -f "$COMPOSE_FILE" logs -f
}

show_status() {
    echo ""
    print_info "Container Status:"
    echo "-------------------------------------------"
    cd "$APP_DIR"
    docker compose -f "$COMPOSE_FILE" ps
    echo "-------------------------------------------"
    echo ""
    print_info "Application URL: http://localhost:3000"
    print_info "Admin Panel: http://localhost:3000/admin"
}

show_help() {
    print_header
    echo "Usage: ./deploy.sh [OPTION]"
    echo ""
    echo "Options:"
    echo "  --init      Initialize fresh deployment (clone repo, create .env, start containers)"
    echo "  --update    Update existing deployment (pull changes, rebuild containers)"
    echo "  --restart   Restart containers without rebuilding"
    echo "  --logs      Show container logs (follow mode)"
    echo "  --status    Show container status"
    echo "  --help      Show this help message"
    echo ""
    echo "Examples:"
    echo "  ./deploy.sh --init      # First time deployment"
    echo "  ./deploy.sh --update    # Update to latest version"
    echo "  ./deploy.sh --logs      # View logs"
    echo ""
}

# Main script
case "${1:-}" in
    --init)
        init_deployment
        ;;
    --update)
        update_deployment
        ;;
    --restart)
        restart_deployment
        ;;
    --logs)
        show_logs
        ;;
    --status)
        show_status
        ;;
    --help|"")
        show_help
        ;;
    *)
        print_error "Unknown option: $1"
        show_help
        exit 1
        ;;
esac
